### ISSUE TITLE
NumberBox query behavior

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase#100]
NumberBox component's query must return `null` when the value is falsy (except for `value === 0`).

**Comment by siddharthlatest** [comment]
In NumberBox, in certain cases, the selected number should inclusive of all higher numbers. For instance: Hotels that can accommodate 2 guests can also accommodate 1 guest.

- [ ] We can support this behavior with an additional prop.

**Comment by siddharthlatest** [comment]
**Update**: We will call this prop `queryFormat`. In NumberBox's case, this prop has two values:

1. "exact" which will apply a term query.  
2. "gte" which will apply a greater than query for values equal to or greater than the current value. (Hotel booking, Airbnb use-case)
3. "lte" which will apply a less than query for values less than or equal to the current value. (Inverse of the 2nd case)

We will also validate that `queryFormat` prop only accepts one of these valid values.

**Comment by farhan687** [comment]
Fixed here: 9116a2df71bbda649275d1330e191d5c1e496902
