### ISSUE TITLE
DataSearch input search term Ux: missing copy/cut/paste/append interactions

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#109]
`DataSearch` and `CategorySearch` which is built on it require users to delete the current search term before adding a new search term. Since search box is just input text, there should be a way to fine-grainely use the cursor to do copy/cut/paste/append interactions.

**Comment by metagrover** [comment]
Fixed here: d19e384cb75d6cf1005e8f379ccaacf15d143f57

**Comment by metagrover** [comment]
Improvements: b21c6cf846f3dcd5525c2c4e0d5f95595880d764
