### ISSUE TITLE
DataSearch Auto Suggestions UX: Truncate excessive text from suggestions

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#110]
Current auto-suggestion look on a field involving phrases of text 
![screen shot 2017-05-25 at 11 00 44 pm](https://cloud.githubusercontent.com/assets/630042/26480220/2919a78e-419e-11e7-8f39-9630f9c75183.png)

We can limit all auto-suggest display items to show up in a single row and end with a "..." if the text is longer. Having a fixed height display would make the UI look more consistent.

**Comment by farhan687** [comment]
Fixed here: 543fd2a0fb06f1342dc8718acb1d583c44033ba0

**Comment by metagrover** [comment]
Improvements: b21c6cf846f3dcd5525c2c4e0d5f95595880d764
