### ISSUE TITLE
MultiList and MultiRange components should have a way to disable tags

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#119]
Now that the `SelectedFilters` component is available, we should disable tags from components that don't need them.

**Comment by metagrover** [comment]
Added `showTags` boolean prop: 16b9917ff306061f7b34ce45758da52a0ef89473

**Comment by metagrover** [comment]
`showTags` prop has now been removed from the specs. Selected values are now controlled via `SelectedFilters` component only.
