### ISSUE TITLE
Support query request when a component has no selected values

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#121]
Scenario:

1. Select a value in a component
   // Network request goes for the query, results are filtered
2. Remove the selection
  // Network request does not go for the query change, results disappear
3. Select the same value in the component
  // Network request does not go for the query change, because it is the same query as 1. and we have cut down on duplicate queries.

One solution is for 2. to make the network request with an empty equivalent query, to prevent the 3. case.

**Comment by farhan687** [comment]
Fixed here: 281b3a6a5262c6393d57eec3807988836ac5cac1
