### ISSUE TITLE
URLParams read issue on NestedList component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#125]
- [x] `NestedList` component is not able to read the set querystring URL Params and set the selection in the component.

- [x] Also, it uses comma (%2C) as a delimiter for separating nested selection path variables. However, a comma can very easily appear in the actual data. Using a forward slash / (%2F) is a better choice for delimiting the path variables of the nested selection.

**Comment by farhan687** [comment]
fixed here https://github.com/appbaseio/reactivesearch/commit/cb4fd935a2584bb45ab96b0996a116c362bfe25c
