### ISSUE TITLE
NestedList: Inner Lists do not show up

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#126]
- [x] Sometimes, inner lists do not show up. Need to look into possible cause as network request does show results returning from the aggs query.
- [x] The item that is clicked disappears and reappears for a second or two when making the first inner aggregation request on it.

**Comment by farhan687** [comment]
fixed here https://github.com/appbaseio/reactivesearch/commit/cb4fd935a2584bb45ab96b0996a116c362bfe25c
