### ISSUE TITLE
DataSearch: Allow html rendering in suggestions to support search term highlighting

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase#128]
![screen shot 2017-06-10 at 5 26 59 pm](https://user-images.githubusercontent.com/9116042/27002526-289abc74-4e02-11e7-9f79-09dff14c1944.png)

**Comment by siddharthlatest** [comment]
Check for the query that goes in suggestions, highlight shouldn't be there.

**Comment by metagrover** [comment]
This was a different issue altogether. Has been fixed here: ebb9601bf3d06f1d98f643a0a78fd9c458f272a1
