### ISSUE TITLE
SelectedFilter component issue

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#129]

**Comment by farhan687** [comment]
Fixed here: 7c793abef69c6111ca017654f4bc7543f48b0a71

**Comment by siddharthlatest** [comment]
@farhan687 We will need to patch one condition here - When a given component has no selected value (often with the case of search), do not display it as a filter.

![](https://i.imgur.com/j6bDBby.png)

See `nestedSearch` component in this case.

**Comment by siddharthlatest** [comment]
Possible place to fix: https://github.com/appbaseio/reactivebase/blob/dev/app/sensors/SelectedFilters.js#L126-L128, this block should be rendered conditionally if the component value is truthy.

The above scenario happens often (even in facets) because of how querystring params currently work.

**Comment by metagrover** [comment]
Hide URLParams and SelectedFilters when empty: bd640825178c6f73e74beb5ce89f9b0bd4f385af
