### ISSUE TITLE
ToggleButton behavior quirks

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#13]
- [x] Add a prop `multiSelect` which defaults to **true** for switch between multiple select and single select modes.
- [x]  Show case as user inputs in the data[i].label prop field. Currently all options are shown in uppercase. ![](https://i.imgur.com/v4BZARn.png)
- [x] CSS: change class names from `title-true` and `title-false` to `rbc-title-active` and `rbc-title-inactive`.
- [x] CSS: add a new class state for multiSelect prop with `rbc-multiselect-active` and `rbc-multiselect-inactive`.
- [x] CSS: btn class in button element should be rbc namespaced.
- [x] CSS logic: there should be a class for button state, like btn-active. Currently, this is done with classes named as blue-grey, light-blue -> this is bad for both usability as well as when extending the components.

**Comment by farhan687** [comment]
Fixed over here 10139dbeb56f37928f9b03062ef40abdfd6effce 344928ab9b165a30cf6384d071ef7ddd97115901
