### ISSUE TITLE
DataSearch component: autocomplete={false} behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#138]
When setting `autocomplete` to false, the search text appears in the autocomplete dropdown although the suggestions do not.

![](https://i.imgur.com/LBbHWd9.png)

Ideal behavior should be to not show a suggestion dropdown in this scenario.

**Comment by metagrover** [comment]
@siddharthlatest  We changed the prop name to `autoSuggest`. Seems to be working fine with that.

**Comment by siddharthlatest** [comment]
@metagrover argh, need to update the docs pretty soon.
