### ISSUE TITLE
RangeSlider CSS issue

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivebase#143]
In `RangeSlider`, `.rc-slider-mark-text` uses a component styling as:
```javascript
style="width: 90%; margin-left: -45%; left: 100%;"
```
This messes up things with the UI when using `rangeLabels` by adding in unnecessary width:
![range-slider-issue](https://user-images.githubusercontent.com/6682655/27471907-089e7e50-5817-11e7-8814-c133d29da9ce.png)

Added this to my style rules to fix but need to check for more cases if the issue persists:
```css
.rc-slider-mark-text
  width 25% !important
  margin-left -15% !important
```

**Comment by metagrover** [comment]
Fixed here: 2a11092
