### ISSUE TITLE
Optimizing Highlight Query:

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#147]
Currently, when multiple search components are a part of the react prop and have different highlight fields, they can cause xN query requests where N is the number of search components with highlight specified.

A better implementation would be to perform a union operation on the highlightfield of all the DataSearch components in the react prop, in the Channel middleware.

**Comment by metagrover** [comment]
Fixed here: feb18d4

**Comment by metagrover** [comment]
Improvements: f7c2cf2c4bf996b340fab062e7bf4cf6ad3a1d14
