### ISSUE TITLE
ReactiveList's meta react fields cause a duplicate query

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#148]
ReactiveList component uses meta react fields like pagination, paginationChanges, streamChanges that get added after the fact, causing an additional network request before the view shows up.

Think of a way to not make the additional network request.

**Comment by siddharthlatest** [comment]
`channelId` should be immutable and the total # of channels should have a one-to-one mapping with the total # of components.

**Comment by metagrover** [comment]
Fixed here: dbadc1ef1980444e5ef218fbfe5173aedada1cf4
