### ISSUE TITLE
DataSearch component: Listening to Changes

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#157]
**DataSearch** component currently does not listen for prop changes. Besides, there are some listening behavior niceties that can be added here.

1. `defaultSelected` prop should have higher pref than URLParams on a change.
2. componentWillReceive should be present to update defaultSelected and other props.
3. customQuery should trigger the reference function call when the prop received generates a different query than the previous prop.

**Comment by metagrover** [comment]
Fixed 1 and 2: b0a121092b3557c0bbfadc8ef561a557cbc92e8f

**Comment by metagrover** [comment]
Fixed 3: 2221bb0
