### ISSUE TITLE
DataSearch: Support more out-of-the-box query conditions

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#163]
- [x] Support `fuzziness` prop which can take auto, 0, 1, 2, ...
- [x] Support `queryFormat` prop which takes **or** and **and**
- [x] Internally optimize the match for loop to instead use a multi_match query, this is not necessary
- [x] #127

**Comment by metagrover** [comment]
Added here: 686769153d3f217dcac3eb89e466e6ab1e371b5d 510a18700b525690bcb60f4413af6c19693540f2
