### ISSUE TITLE
Remove jQuery dependency (if possible)

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase#166]
It seems that jQuery takes up 14.6% of the UMD build (most recent), if we can get rid of jquery, we should be able to shrink it even further.
![screen shot 2017-07-14 at 2 37 59 pm](https://user-images.githubusercontent.com/9116042/28206092-4f721684-68a2-11e7-8987-fb371ec2384a.png)

**Comment by metagrover** [comment]
It not possible, we should anyway kick out jQuery from the UMD build and ask the client to load it via CDN.

**Comment by divyanshu013** [comment]
Are we mainly using jQuery for ajax?

**Comment by metagrover** [comment]
Not sure, but it is spread out across all the sensors/actuators. Will need a careful re-write at some places.

**Comment by metagrover** [comment]
Fixed here: e1c6664
