### ISSUE TITLE
onValueChange behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#173]
Is there a way to make `onValueChange` prop to complete the execution cycle before invoking the query execution for the component or it's react dependent components?

### Use-case:

Using a component's value to use one or more components exclusively.

**Comment by metagrover** [comment]
Added `beforeValueChange` prop here:

81536c87ffb6abaa719e714d80349d100e56ebc4 dd59de1bf4b874e30e67c06b58c783febe331a93 1f2f272e79b48cfad6a76b27d015cfc545db3f39 4f70ebfe09c85a51b2b77b4aa33133eed00e4522 1b9a50e8e54a055e4eb518b4b165d592a1b789cd 49e4516d8707d472b41f0b56bf05392041862b6f 2ff590f5d2f3ca60269c9e84e04c40243fc0dd90 f6cd63dcf2151dca73460fc009147c056305beb0 aefe66c42e78de7e13a4e07a2be71105ace77830 0d052083ca8f14999aa15c37f94ea4043d3cabb3 25abc2dca680aabf738dd981a2bcfef84df993ca e5e50e1009fb11c0f837bb88b623a299d34837ca d96bb69fea91235f31c2f1a8554bcee300f4107d 155decf6274e1e22c3956b3a6c52060ee8ae2eea 69eaeca14b4f10a880797fc55cf21705ce8c4902 964d5cdd5c602fb609759e26ffa824d67d26509c 1f1cbe4a47f1a5514f00ab758e02ac3655b65296
