### ISSUE TITLE
RangeSlider only shows results in stepInterval ignoring the URLParams end value

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivebase#183]
Say a `RangeSlider` component has a `stepValue={100}` and the `start` and `end` values passed are `0` and `250`, then the component will only consider the values in the intervals of `100` to display the final result, i.e. it'll round of the values to hundreds (270 will be treated as 200, 230 as 200 and so on).

e.g. [this](https://appbaseio-apps.github.io/gitxplore/?forks=%7B%22start%22%3A**0**%2C%22end%22%3A**250**%7D) link https://appbaseio-apps.github.io/gitxplore/?forks=%7B%22start%22%3A0%2C%22end%22%3A250%7D should give the repos having `forks` in range of `0 to 250` and the concerned RangeSlider component has `stepValue={50}`. But if we pass the end to say `290`, we will get the same results we got for `250` (since it was a multiple of the `stepValue`).

I think the RangeSlider should take the URL into account with the actual value passed and not a multiple of `stepValue`. This makes linking to the app easier from some other domain. If it's an expected behavior, we could mention it in the docs. I ran into this problem trying to correctly link the charts from [this](https://codepen.io/divyanshu013/pen/PKmOdY?editors=0010) pen for a long time before I realised the cause of the problem.

**Comment by metagrover** [comment]
In such cases, anomalies are logged as warnings in the console.
