### ISSUE TITLE
Add missing stories and knobs to storybook

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivebase#186]
- [x] `SingleDataList/MultiDataList` `defaultSelected` working but when nothing is matching the selected value should get removed

**Comment by siddharthlatest** [comment]
@divyanshu013 We don't have knobs supported yet.

- [ ] We need to add knobs for reactivebase component stories. All stories should ideally support the knob value that the story is about.

- [ ] The playground story of the component should contain all props that are listed in the reference doc for that story. As an example, SingleList playground should have `filterLabel` knob.

**Comment by divyanshu013** [comment]
Above commits fixes the issues
