### ISSUE TITLE
RangeSlider: beforeValueChange receives an undefined value

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#191]
The `beforeValueChange` prop in the RangeSlider component receives an undefined value when the value of the component is being changed. The initial value it receives (on component initialization based on defaultSelected) is correct, but every change after is returned as undefined.

It also throws an uncaught error in the component's implementation.

![](https://i.imgur.com/KS0Qh6p.png)

**Comment by metagrover** [comment]
Fixed here: f7e2f6f
