### ISSUE TITLE
Dynamically update highlight in DataSearch

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivebase#198]

**Comment by siddharthlatest** [comment]
@divyanshu013 What is the issue about?

**Comment by divyanshu013** [comment]
This happens when we toggle `highlight` prop. Currently when the query remains the same the highlight prop isn't updated probably due to channel manager. So after toggling highlight prop we have to type in some other query to see the highlight getting reflected.
For example on the [playground example](https://opensource.appbase.io/playground/?knob-highlight=true&selectedKind=search%2FDataSearch&selectedStory=With%20highlight&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs) this can be seen.

@metagrover can explain better about the channel manager logic

**Comment by divyanshu013** [comment]
Fixed in reactivesearch v2, related https://github.com/appbaseio/reactivesearch/issues/81
