### ISSUE TITLE
SelectedFilters component: UI display

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#203]
- [x] Restrict max-width to 200px on a mobile viewport
- [x] Have a higher width for desktop viewports: 400px, add a tooltip on each filter that shows the complete value.

**Comment by metagrover** [comment]
[1] d2115ffe6c21f5a24848f8d695c7ca1dc4944112

**Comment by metagrover** [comment]
[2] Updated here: cbd8968
