### ISSUE TITLE
Update breaking prop defs

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#205]
We have made some breaking and some non-breaking changes. The docs are up-to-date with the to be released `1.0.0` version. The same has to be applied to the following places (could be more):

- [x] ReactiveMaps examples
- [x] ReactiveSearch examples
- [x] Published blog post: codepen links
- [x] Onboarding tutorial and their codepen links
- [x] ReactiveBase playground and examples
- [x] appbaseio/playground repository
- [x] ReactiveSearch starter app
- [x] ReactiveMaps starter app

**Comment by divyanshu013** [comment]
Playground updates in https://github.com/appbaseio/playground/commit/4f1db07f659b05939ee4ce8610e36d8fc73f8266

**Comment by divyanshu013** [comment]
Updated codepens at https://codepen.io/collection/DggOOZ/

**Comment by metagrover** [comment]
Reactivebase examples and stories updated here: e994c338e7a59a9f6ba7c2a24f63d6f4907d7ee6

**Comment by metagrover** [comment]
Reactivemaps examples and stories updated here: https://github.com/appbaseio/reactivemaps/commit/06815c491266a5424e247d3aa1c92826339d49e0

**Comment by metagrover** [comment]
Reactivesearch examples and stories updated here: https://github.com/appbaseio/reactivesearch/commit/19c0adad21a9e806bcb777c2df1d286b6838d2cf

**Comment by metagrover** [comment]
Updated Airbeds onboarding: https://github.com/appbaseio-apps/airbeds-onboarding/commit/c0d69bd1747a9d803b1ce28e6c1dee69a42cf376

**Comment by metagrover** [comment]
Updated Reactivesearch onboarding here: https://github.com/appbaseio-apps/reactivesearch-onboarding/commit/efe3f077375ce7154bd4102f44011112c5c6db97

**Comment by metagrover** [comment]
Codepens updated here: https://codepen.io/metagrover/pens/public/

**Comment by divyanshu013** [comment]
:white_check_mark: Updated gitxplore-onboarding at https://github.com/appbaseio-apps/gitxplore-onboarding/commit/46d216fb5625ba9a37f190d4013f17ee49a72dae
:white_check_mark: Updated gitxplore app at https://github.com/appbaseio-apps/gitxplore/commit/a1e765d79e16815d525271b1f86e85c841e061e0
:white_check_mark: Updated gitxplore pens at https://codepen.io/collection/DQGazB/
:white_check_mark: Updated gitxplore blog post at https://medium.appbase.io/how-to-build-a-github-search-ui-in-60-minutes-295109211c70?source=collection_home---3------1----------------
