### ISSUE TITLE
standardize value object being passed in onValueChange

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivebase#207]
All the sensor components should have a consistent value passed to the callback function. And we should include the necessary details depending on the component. For example, a range slider component should pass both start and end with value.

TODO: Compile a list of values sent in all sensors and change wherever needed

**Comment by divyanshu013** [comment]
### DataController
Recieves the value as a `string`. eg-
```
Default
```

### DataSearch
Recieves the value as a `string`. eg-
```
Home
```

### DatePicker
Recieves the value as a `Moment` object. eg-
```
Moment {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: Locale, _d: Tue Sep 05 2017 12:00:00 GMT+0530 (IST)…}
```

### DateRange
Recieves the value as an object with `startDate` and `endDate` keys having `Moment` object as values. eg-
```
{startDate: Moment, endDate: Moment}
```

### MultiDataList
Recieves the value as an array of `string` values. eg-
```
["Travel", "Outdoors"]
```
When nothing is selected returns an empty array `[]`

### MultiDropdownList
Recieves the value as an array of `string` values. eg-
```
["London", "San Francisco"]
```
When nothing is selected returns `null`

### MultiDropdownRange
Recieves the value as an array of `object`. eg-
```
[
  {
    "start": 101,
    "end": 200,
    "label": "Moderate",
    "value": "Moderate"
  },
  {
    "start": 0,
    "end": 100,
    "label": "Cheap",
    "value": "Cheap"
  }
]
```
When nothing is selected returns `null`

### MultiRange
Recieves the value as an array of `object`. eg-
```
[
  {
    "start": 0,
    "end": 100,
    "label": "Cheap"
  },
  {
    "start": 101,
    "end": 200,
    "label": "Moderate"
  }
]
```
When nothing is selected returns `null`

### SingleList
Recieves the value as a `string`. eg-
```
Los Angeles
```
When nothing is selected returns `null`

### MultiList
Recieves the value as an array of `string`. eg-
```
["Social", "Computer programming"]
```
When nothing is selected returns `null`

### NumberBox
Recieves the value as an `object`. eg-
```
{value: 8, queryFormat: "gte"}
```

### RangeSlider
Recieves the value as an `object`. eg-
```
{from: 2, to: 8}
```

### SingleDataList
Recieves the value as a `string`. eg-
```
Social
```
When nothing is selected returns `null`

### SingleDropdownList
Recieves the value as a `string`. eg-
```
Melbourne
```
When nothing is selected returns `null`

### SingleDropdownRange
Recieves the value as an `object`. eg-
```
{start: 0, end: 100, label: "Cheap", value: "Cheap"}
```
When nothing is selected returns `null`

### SingleRange
Recieves the value as an `object`. eg-
```
{start: 101, end: 200, label: "Moderate"}
```
When nothing is selected returns `null`

### TextField
Recieves the value as a `string`. eg-
```
audi
```
When nothing is selected returns empty string `''` and when filter is removed returns `null`

### ToggleButton
Recieves the value as an array of `object`. eg-
```
[{"label":"Travel","value":"Travel"}]
```
When nothing is selected returns `null`

**Comment by siddharthlatest** [comment]
@divyanshu013 

- [ ] We can standardize `null` as the return value when nothing is selected.
- [ ] For RangeSlider, the value returned should be an object with `start` and `end` as keys.

**Comment by siddharthlatest** [comment]
@metagrover can we follow a similar format across ReactiveSearch components too in case we aren't doing so?

**Comment by metagrover** [comment]
@siddharthlatest Sure thing!
