### ISSUE TITLE
Support native events for Input fields

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#210]
- [x] TextField
- [x] DataSearch
- [x] CategorySearch

Example events: onFocus, onBlur, onKeyDown, onKeyUp, ...

- [x] Update the docs

**Comment by siddharthlatest** [comment]
@divyanshu013 @dhruvdutt Have we updated the docs for these?

**Comment by divyanshu013** [comment]
Docs are not updated @siddharthlatest with the native events. I can add them, which section should we add them to?

**Comment by siddharthlatest** [comment]
@divyanshu013 They should be in the Extending section.

**Comment by divyanshu013** [comment]
Added in https://github.com/appbaseio/reactive-manual/commit/2ede16cb1a0a4377ac42a140e9937ad0890ed643, https://github.com/appbaseio/reactive-manual/commit/f927bff9f8bb3485c2a16f97a713b61e97dbe501 and https://github.com/appbaseio/reactive-manual/commit/6ccc94e079dfb476a53ee74ae29a719ab98fa083
