### ISSUE TITLE
Compatibility with CRA

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#212]
Ensure that ReactiveSearch also works with a CRA boilerplate app.

**Comment by dhruvdutt** [comment]
The issue seems to be with shebang/sha-bang in the [JSONStream lib](https://github.com/dominictarr/JSONStream/blob/master/index.js#L1).
A related issue: [#4603](https://github.com/webpack/webpack/issues/4603)

**Comment by divyanshu013** [comment]
Verified compatibility of ReactiveSearch using CRA. @metagrover's rewrite of appbase-js should help us get rid of JSONStream from the dependencies

**Comment by divyanshu013** [comment]
Reactive<x> works out of the box with CRA now :ok_hand:
