### ISSUE TITLE
Behavior of DataSearch component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#22]
- [x] DataSearch component should support `title` prop.
- [x] DataSearch component should not have a `depends` prop.
- [x] `autocomplete` prop which decides whether autocomplete is applied, defaults to `true`.
- [x] `appbaseField` should take either a String or an Object Array of valid fields (order not relevant).

```
<DataSearch 
    appbaseField={["field 1", "field 2", .. , "field n"]}
... />
```
- [x] Use regular fonts for displaying input text, no italics ![](https://i.imgur.com/BeOtXMl.png) and placeholder style should be consistent with other components (i.e. no bold). ![](https://i.imgur.com/72lpFzI.png)
- [x] Bring outer style consistency with `TextField` component. ![](https://camo.githubusercontent.com/a3ca674ff59430f898a36e584a587a0c406230ca/68747470733a2f2f692e696d6775722e636f6d2f65566338754c492e706e67)

**Comment by metagrover** [comment]
Fixed here e65a03aed450766aa456cc76c0a4bb7f04bbdeb9
