### ISSUE TITLE
react prop dependency triggering multiple queries

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#229]
Component's internal request is being fired without waiting for the react prop's first set of query building, i.e. if component A has a react prop with component B in it, and component B has a defaultSelected or URLParam set, component A triggers two requests where ideally it should've triggered a single one.

**Comment by metagrover** [comment]
Fixed here: acca326 @siddharthlatest can you verify? 

PS: This should also resolve #154
