### ISSUE TITLE
ToggleButton stream issue

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactivebase#230]
Using [ToggleButton](https://opensource.appbase.io/reactive-manual/v1.0.0/components/ToggleButton.html) with [TodoMVC app](https://appbaseio-apps.github.io/todomvc/#/), stream enabled and a custom query.
```jsx
<ToggleButton
  ...
  stream={true}
  customQuery={
    function(data) {

      // computations based on current tab selection. completed = "all" || true || false
      const completed = ...

      if (completed === "all") {
        return {
          query: {
            match_all: {}
          }
        }
      }

      return {
        "query": {
          "bool": {
            "must": [
              {
                "match": {
                  "completed": completed
                }
              }
            ]
          }
        }
      }
    }
  }
</ToggleButton
```

The streaming works fine with `match_all` query but doesn't work properly in other queries like `match` or `term`.

The streaming works fine in some cases like: :white_check_mark: 
  - Editing an existing todo `title`
  - Editing existing todo's `completed` status which evaluates to be in the current tab
  - Adding a completely new todo

It doesn't work when: :x: 
  - Toggling a todo (should remove it from the current tab)
  - Deleting a todo

> Links: [Code](https://github.com/appbaseio-apps/todomvc/), [Dejavu](https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAALbAAAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsxU8Ys6_ZhvS2-thHb6dtT3lGtp5oxI8n549wxVg2S5nb7iqLsa0U4Vuny8dCL1oJzzaawZ97XMtfP1x1Rwyduj4KiL7UvQK7bDn6bStLh0H-ZVCZ-YTEvc_0wjXH6dQAPq0GSX_V4NJ_7BppACwni07_eogCXU-2EaWaeuLAgBXTNTOBCnJsRoWvUrTeVlQvBZJJwz-9cytgO6ubiQpLPoa9NhC_9PWQAA), [Mirage](https://opensource.appbase.io/mirage/#?input_state=XQAAAAKwBAAAAAAAAAA9iIhnNAWbsswtYjeQNZkpzQK4_mOzUeDpWmKy6bA5agSYe1JiQgfkiNA7gw2HgoIIiFTTsA9ZyZY5VhBROEhMYAp9wXmbYO9ipNHXRV-VJgm6LuM5E2bVn4BJNpAxaYUWLLKKe3yh7cC96SxlNSC5VxlND1nRcJtpqGMwECOdRceO0xWgoXoyDliq_NpQ5H5RQaKgR1jfzT6Rt2HW2FlGRoS8Y0qz_2fvgqciRE812XeKB23dnSg9YesZ2pfah8TUGmlj_3XgJGAWOgmAekp3gIxqe-ABYWiRAz-DgiPTc05bNCmiOQoiqkdns1U_qycNDbza3M1jVaZwomDM6rMLtlwgGtkBCJFnsU2LjOYoqfc4ZPjdSY0xDEniWUU3U9fqK0vrjgqA9B_hd02hqkyapDpEadu2G65nRjKysBtt9G0GzM_VRkGGinLz52-6211XExEcKDN7jHoltvDqINg4hK1YK4RS1SD-8_pA4dr3gmAsNBm0V2GuNIMpnl18zEBu6MpEA7_cQxjTrLAhlUHrJmVsK96Zl1FosG1DKgN-yTk6XdJA1zpNBmrv3w1oJTCwkBHQkbez7iIlLT29n_DzQ9gieJiQJbJzFKs9VQ024bN6Hk99kmp14_QVeT3xs1-McFIVHFnnLTL8nmx1h__X3w2_)

**Comment by dhruvdutt** [comment]
I think the results are streamed only when there is some new data on the query.

Eg. When we're running `"completed": "false"`, we get all todos those have _completed: false_. In the case when a todo is toggled, its status changes to _completed: true_ and hence may not be reflecting on the streaming data as it doesn't evaluate to be valid on the query.
When we update an existing todo's status from _true_ to _false_, it satisfies the query and we get the streaming result with `"_updated": true`. In the case when it's switched from _false_ to _true_, we should ideally stream it with `_updated` or `_deleted` flag.


Also in the case when a todo that was part of historic stream with status _false_ it is deleted, the streaming should happen with `_deleted: true` which doesn't happen.

To reproduce these cases:
  - Go to [Mirage](https://opensource.appbase.io/mirage/#?input_state=XQAAAAKwBAAAAAAAAAA9iIhnNAWbsswtYjeQNZkpzQK4_mOzUeDpWmKy6bA5agSYe1JiQgfkiNA7gw2HgoIIiFTTsA9ZyZY5VhBROEhMYAp9wXmbYO9ipNHXRV-VJgm6LuM5E2bVn4BJNpAxaYUWLLKKe3yh7cC96SxlNSC5VxlND1nRcJtpqGMwECOdRceO0xWgoXoyDliq_NpQ5H5RQaKgR1jfzT6Rt2HW2FlGRoS8Y0qz_2fvgqciRE812XeKB23dnSg9YesZ2pfah8TUGmlj_3XgJGAWOgmAekp3gIxqe-ABYWiRAz-DgiPTc05bNCmiOQoiqkdns1U_qycNDbza3M1jVaZwomDM6rMLtlwgGtkBCJFnsU2LjOYoqfc4ZPjdSY0xDEniWUU3U9fqK0vrjgqA9B_hd02hqkyapDpEadu2G65nRjKysBtt9G0GzM_VRkGGinLz52-6211XExEcKDN7jHoltvDqINg4hK1YK4RS1SD-8_pA4dr3gmAsNBm0V2GuNIMpnl18zEBu6MpEA7_cQxjTrLAhlUHrJmVsK96Zl1FosG1DKgN-yTk6XdJA1zpNBmrv3w1oJTCwkBHQkbez7iIlLT29n_DzQ9gieJiQJbJzFKs9VQ024bN6Hk99kmp14_QVeT3xs1-McFIVHFnnLTL8nmx1h__X3w2_), run streaming query.
  - Go to [Dejavu](https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAALbAAAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsxU8Ys6_ZhvS2-thHb6dtT3lGtp5oxI8n549wxVg2S5nb7iqLsa0U4Vuny8dCL1oJzzaawZ97XMtfP1x1Rwyduj4KiL7UvQK7bDn6bStLh0H-ZVCZ-YTEvc_0wjXH6dQAPq0GSX_V4NJ_7BppACwni07_eogCXU-2EaWaeuLAgBXTNTOBCnJsRoWvUrTeVlQvBZJJwz-9cytgO6ubiQpLPoa9NhC_9PWQAA)
    - Update a todo from `false` to `true`
It won't stream results as the change doesn't evaluate to be true on the query.
    - Delete a todo
It should ideally stream result with `_deleted: true`

**Comment by siddharthlatest** [comment]
@dhruvdutt 

> Eg. When we're running "completed": "false", we get all todos those have completed: false. In the case when a todo is toggled, its status changes to completed: true and hence may not be reflecting on the streaming data as it doesn't evaluate to be valid on the query.
When we update an existing todo's status from true to false, it satisfies the query and we get the streaming result with "_updated": true. In the case when it's switched from false to true, we should ideally stream it with _updated or _deleted flag.

The first part of the behavior is how streams currently work. They only update or create a new stream event when the query condition is matched.

> Also in the case when a todo that was part of historic stream with status false it is deleted, the streaming should happen with _deleted: true which doesn't happen.

You are testing this from dejavu, which applies a bulk delete request. If you do the delete request from the REST API, it actually streams the `_deleted: true` event.

Overall, this isn't an issue.
