### ISSUE TITLE
Update to React 16.0.0

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactivebase#232]
We currently have `"react": "^15.4.2"` in [peerDependencies](https://github.com/appbaseio/reactivebase/blob/dev/package.json#L43) and [devDependencies](https://github.com/appbaseio/reactivebase/blob/dev/package.json#L88)

React version changelogs since then:
- [v15.5.0](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#changelog)
- [v15.6.0](https://reactjs.org/blog/2017/06/13/react-v15.6.0.html#changelog)
- [v16.0.0](https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes)

**Comment by dhruvdutt** [comment]
Deps that require updates:
- react-dates: `^4.3.0` to `^12.6.0`
  - DatePicker, DateRange: Breaking UI, unknown props found: id

- rc-slider: `^5.4.0` to `^8.3.1`
  - RangeSlider: Works after changing `<Slider range ... />` to `<Range ... />`

- storybook-readme: `^3.0.5` to `^3.0.6`

**Comment by metagrover** [comment]
Updated here: #233 and 889ea4d137d096f5c5f0ddac540f46ea96f85843
