### ISSUE TITLE
Replace doc links in stories

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#236]
Link structure has changed from

`import GeoDistanceSliderReadme from "@appbaseio/reactivemaps-manual/docs/v1.0.0/map-components/GeoDistanceSlider.md"`

to

`import GeoDistanceSliderReadme from "@appbaseio/reactivemaps-manual/docs/v1/map-components/GeoDistanceSlider.md"`

```
s/v1.0.0/v1
```

**Comment by harsanyizoli** [comment]
In which file does it need to be changed?

**Comment by siddharthlatest** [comment]
This should be inside the https://github.com/appbaseio/reactivebase/tree/dev/app/stories dir.

If you are planning to take the issue, be sure to self-assign and submit as a PR when ready.

**Comment by harsanyizoli** [comment]
I have no idea how to self assign but i made a pull request. I am new to it so hopefully it works

**Comment by divyanshu013** [comment]
Resolved in ebc8495980f5f57448667aaf47ef977ab382d094
