### ISSUE TITLE
Simple connection to url

### ISSUE THREAD

**Issue by adelin-b** [appbaseio/reactivebase#247]
Hello ! Im stuck for a while now because Im trying to use my google cloud bitnami elastic search instance

https://codesandbox.io/s/0xppmylypn 

here is my elasticsearch.yml in my cloud instance 
```
cluster.name: elasticsearch

network.host: 0.0.0.0
network.publish_host: 35.204.178.123

http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-origin: "http://35.204.178.123/elasticsearch/:80"
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Contro
l-Allow-Headers, Accept
```

However it doesnt seem to get the authorization.
Any idea ?

**Comment by siddharthlatest** [comment]
Hi @adberard, the `http.cors.allow-origin` address should point to the domain where your ReactiveSearch app is running. Other things look okay on a first glance.

**Comment by adelin-b** [comment]
Thanks for confirming that everything seem correct. 
I tryed with "*" but still not work yet. I may have other configs failing

**Comment by adelin-b** [comment]
Is there any example of this working with the url props ?

**Comment by britishbadger** [comment]
Did you manage to get this to work, we are seeing the same. 
1. Docker container has ES
2. running yarn start for reactivesearch (http:///localhost:3000)

Following props set :
- http.cors.allow-origin="*"
- http.cors.allow-headers="Access-Control-Allow-Origin,X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
- http.cors.allow-credentials=true

**Comment by adelin-b** [comment]
No Im sorry didn't. Please keep me up if you manage to do it.

**Comment by siddharthlatest** [comment]
@britishbadger what version of ES are you running - mind sharing the docker run command? Will try to replicate and get back.

**Comment by britishbadger** [comment]
I actually got this working, we are using docker compose, working snippet for others below. 

One of the environment parameters must have been wrong. I've gone with * as it was just a prototype, but would obviously set accordingly. 

I was using ```yarn start``` 

``` # snippet
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
```

**Comment by stonesthatwhisper** [comment]
@britishbadger this does not work for me actually, for ES 7.5. ReactiveBase has this error with `yarn start` running on `localhost`:

`Access to XMLHttpRequest at 'https://<subdomain-name>/<index>/_msearch?' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

    es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - node.name=es00
      - discovery.type=single-node
      - VIRTUAL_HOST=<subdomain-name>
      - VIRTUAL_PORT=9200
      - LETSENCRYPT_HOST=<subdomain-name>
      - LETSENCRYPT_EMAIL=it@domain-name.com
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Length,Content-Type,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data00:/usr/share/elasticsearch/data`
