### ISSUE TITLE
DataSearch component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#25]
- [x] Remove the `sensorInputId` prop and its related codebase.
- [x] Component style should be consistent b/w when autocomplete is enabled and disabled.

**Comment by metagrover** [comment]
Fixed here: 39e51fa4e72c29958a30ab2580d3b1e69e528e83 1d0e0b245c89135f128472fb98b2375158af5c07 a2f5dd78a31d631e4815f4d359b2d94f73d256cf
