### ISSUE TITLE
MultiList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#26]
- [x] Standardize "Select All" using `selectAllLabel` prop. When selecting all, all the list items should be checkbox selected.
- [x] When count is set, show `rbc-count-active`. When set to false, show `rbc-count-inactive` in the top level element.
- [x] Replace `searchPlaceholder` prop with `placeholder`.
- [x] When list `size` > 5, replace the individual filter labels with a `Clear All` filter label.
- [x] Validate `size` prop to accept values in the range [0, 1000].
- [x] Validate `sortBy` prop to accept one of ("count", "asc", "desc")  values.
- [x] `size` and `sortBy` props should re-render the component in storybook's playground.

**Comment by farhan687** [comment]
Fixed 6ef9a5cb34d3fc877a8aecdcb93aab983f54b1d0
