### ISSUE TITLE
SingleList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#27]
- [x] Standardize "Select All" using `selectAllLabel` prop. When selecting all, all the list items should be checkbox selected.
- [x] When count is set, show `rbc-count-active`. When set to false, show `rbc-count-inactive` in the top level element.
- [x] Replace `searchPlaceholder` prop with `placeholder`.
- [x] Validate `size` prop to accept values in the range [0, 1000].
- [x] Validate `sortBy` prop to accept one of ("count", "asc", "desc")  values.
- [x] `size` and `sortBy` props should re-render the component in storybook's playground.

**Comment by farhan687** [comment]
Fixed here: e4e54b4bf8fee0c9df16778fa6b53c06b8f54aac
