### ISSUE TITLE
NestedList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#28]
- [x] remove `multipleSelect` prop
- [x] remove `includeSelectAll` prop
- [x] remove `defaultQuery` prop
- [x] `sortBy` prop should accept only one of ("count", "asc", "desc") string values.
- [x] `size` prop validation: should accept numeric values between [1, 1000].
- [x] `defaultSelected` prop should be validated as an Array.
- [x] setting `showCount` prop to false should disable count from view.

**Comment by farhan687** [comment]
Fixed over here: 71104f77266ac01c9782f37035bcbd246e94e91d, bcb94f6aab2bb89e4e7afa6ec76a2d95e0bb399c, 88a6c6b928a6633844cf0cb9d0ef419cf2cf19dc

**Comment by siddharthlatest** [comment]
- [ ] In CSS styles, use `rbc-label` class for the label's <span> element and replace `rbc-sub-nestedlist` with `rbc-sublist-container`

**Comment by metagrover** [comment]
Fixed here 748bff31a74091dda5834f08f6ba8c59ae2975fc
