### ISSUE TITLE
RangeSlider component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#29]
- [x] Replace `startThreshold`, `endThreshold` with a `threshold` object.
- [x] `threshold` prop should be validated for accepting only numeric values in it's *start* and *end* keys, and end >= start.

**Comment by farhan687** [comment]
Fixed over here: f3ecd243be78f96637e743aec8dc28a298bb36f1

**Comment by siddharthlatest** [comment]
@farhan687 the slider in the RangeSlider component doesn't work within storybook.

**Comment by siddharthlatest** [comment]
We will also replace

- [ ] `threshold` object prop with `range` object prop. (only the name changes)

**Comment by siddharthlatest** [comment]
@farhan687 what does `size` prop do?

**Comment by metagrover** [comment]
Fixed here: 54f0e7b90401d65c696a17751aad7deb85aaf7c9 3aa20d0dd42260cc3c88fc6b7ce0b45caa93e6bb 5e776f4d9c1e32a82d90d187acb47250b8f1a1d6 f5b7448b0728a5bf595b399b0c30da7d8c03d8a0

**Comment by siddharthlatest** [comment]
- [ ] Use custom labels v/s the labels provided by rc-slider due to inconsistency in stepValue's UI behavior when using rc-slider's label props.
