### ISSUE TITLE
MultiDropdownList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#32]
- [x] `size` prop should be validated to be between [1, 1000].
- [x] Replace `searchPlaceholder` prop with `placeholder`.
- [x] `sortBy` prop should be validated to be one of ("asc", "desc", "count") string values.
- [x] `showCount` prop should work.
- [x] `size` and `sortBy` props should re-render the component in storybook playground mode.
- [x] When count is set, show `rbc-count-active`. When set to false, show `rbc-count-inactive` in the top level element.

**Comment by metagrover** [comment]
Fixed here a6893ab51aa52cc55136ce53cc23a223d09871ae
