### ISSUE TITLE
apply rbc-placeholder-active / rbc-placeholder-inactive classes

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#34]
Depending on the placeholder state (whether present or absent), apply `rbc-placeholder-active` and `rbc-placeholder-inactive` classes.  

Applicable components:  

- [x] SingleList
- [x] MultiList
- [x] SingleDropdownList
- [x] MultiDropdownList
- [x] NestedList
- [x] TextField
- [x] DataSearch

**Comment by metagrover** [comment]
Fixed here: 6a0498f3a327cba841d6f62454312ccfbf543453 748bff31a74091dda5834f08f6ba8c59ae2975fc
