### ISSUE TITLE
PaginatedResultList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#37]
- [x] need to support `sortOptions` prop. When it is enabled, a `rbc-sortoptions-active` class will be set. When not, a `rbc-sortoptions-inactive` class will be set.
- [x] `requestOnScroll` prop should not be exposed to the user. It should be set to **false** internally.
- [x] `componentStyle` prop should be added for adding styles to the top-level component element.
- [x] `from` prop validation: should be a `Number` >= 0.
- [x] `size` prop validation: should be `Number` >= 1.
- [x] When user does not specify the onData callback, a default UI similar to the one in ResultList component should appear. We should add a story for this.

**Comment by siddharthlatest** [comment]
@metagrover @farhan687 Should the main class for this component be `rbc-resultlist` (which is currently happening) or `rbc-paginatedresultlist`?

**Comment by siddharthlatest** [comment]
Similar to ResultList component's issue, it makes sense for us to think about doing this for keeping a consistent CSS styles API as well as applying theming effects on.

- [ ] Wrap the array of HTML elements returned by the `onData` function inside a div with a `rbc-list-item` class.

**Comment by farhan687** [comment]
Fixed here: 0f91e67b753387550142dad4885ea5f8005f889f
