### ISSUE TITLE
ResultList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#38]
- [x] validate `from` prop to be a Number >= 0.
- [x] validate `size` prop to be a Number >= 1.
- [x] validate `sortBy` prop to only accept either `asc` or `desc` values.
- [x] When `stream` is true, use css class `rbc-stream-active`. When false, use class `rbc-stream-inactive`.
- [x] When `sortOptions` prop is enabled, a `rbc-sortoptions-active` class will be set. When not, a `rbc-sortoptions-inactive` class will be set.

This is something we have talked once, but it makes sense for keeping a consistent CSS styles API as well as applying theming effects on.

- [x] Wrap the array of HTML elements returned by the `onData` function inside a div with a `rbc-list-item` class.

**Comment by farhan687** [comment]
Fix here: 301ca1ac3fe790e2e6fad7b43d8f519e1c8390f4
