### ISSUE TITLE
Create a NumberBox component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#39]
A **NumberBox** UI widget is useful for travel search experience websites like Kayak, as well as in an e-commerce setting for deciding quantities of an item in the cart.

![Number box use on kayak.com](https://i.imgur.com/l99szja.png)

### Props Spec

**componentId** `String`
    id of the component, referenced inside an actuator query.
**appbaseField** `String`  
    sets the DB field to be mapped with the UI component view.
**title** `String` [optional]  
    sets the title of the the component.
**data** `Object`  
    sets the `label` and associated `start` and `end` values.
**labelPosition** `String` [optional]  
    sets the label position, available options are "left", "right", "top", "bottom". Defaults to "left".
**defaultSelected** `Number` [optional]  
    sets the initial value of the NumberBox. Defaults to the `start` value in the data object.

### CSS Styles API Spec

**State Classes** 

* `rbc-title-active` / `rbc-title-inactive` depending on if the `title` prop is set.
* `rbc-label-left` / `rbc-label-top` / `rbc-label-bottom` / `rbc-label-right` depending on the `labelPosition` prop's value.

The component will use a term query behind the scenes to do an exact match on the selected value.

**Comment by metagrover** [comment]
Added here: 3f0ab6b2b037c90b6643f5c9662dd1a538908f23 d7c9645d6c31e460715cb89bf900b9cee5fd97a1
