### ISSUE TITLE
Create a <div> ReactiveElement actuator component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#46]
# Props

* componentId
* title
* react
* placeholder
* onData

# Styles

rbc-reactiveelement
rbc-title-active / rbc-title-inactive
rbc-placeholder-active / rbc-placeholder-inactive

Compatible with `light` and `dark` themes.

**Comment by farhan687** [comment]
Fixed here and created new stories for ReactiveElement: 8ad2e65dacb01c2d5b4fe5871ed5e814f365ee8f
