### ISSUE TITLE
ReactiveList component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#49]
- [x] Fix height for ResultList when no results and when size is <5. (check prop changes)
- [x] size prop is not changing dynamically in storybook.
- [x] Streams results even when no filter is selected.

**Comment by farhan687** [comment]
Fixed here: ac6c24710aa6828490b8567d132c2e4dff103034

**Comment by siddharthlatest** [comment]
- [ ] When ReactiveList hits the end of the results, the animation spinner should not appear.
- [ ] ReactiveList's scroll should be reset when the query changes.

**Comment by farhan687** [comment]
Fixed here: ac2f6e886c816b6f5b4a0ecb04d8f39abde5f272 e17a84d6cd5afccd035876383cf6e6966da7f122
