### ISSUE TITLE
Showing sort options in the UI for ResultList

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#5]
Showing sort options in the UI for `ResultList` component. We support three options: 

1. default (sort by relevance)  
2. asc (sort by ascending order of the `appbaseField` prop)  
3. desc (sort by descending order of the `appbaseField` prop)

**Comment by metagrover** [comment]
Added here bfc4eac366c5f80e34ca9401a110924b02b7a597
