### ISSUE TITLE
New component: ResultStats

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#54]
- [x] Show `total` and `time taken`.

**Comment by farhan687** [comment]
Fixed here: 0c72a101907c2bf328f01fa96d25f4e96cacae8d 68e695805fb1f7d942dff15a5a25ab15ad298541

**Comment by siddharthlatest** [comment]
Supports `onResultStats` prop, which takes a function with two parameters `time_taken` and `total` and returns a string which will be displayed in the actuator component's UI.
