### ISSUE TITLE
MultiList sensor behavior

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase#56]
Deletion in `defaultSelected` prop does not update the tags. Changes are reflected only in the Checkbox List.

![screen shot 2017-02-19 at 9 03 56 pm](https://cloud.githubusercontent.com/assets/9116042/23103796/fb61c4fe-f6e6-11e6-8854-5ff3cd3c4de2.png)

**Comment by farhan687** [comment]
Fixed here: 226cfea08b3d255dc0d032c84aec023856913c8c
