### ISSUE TITLE
Use defaultSelected prop in Date components

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#58]
- [x] DatePicker uses defaultSelected prop which takes a moment() object
- [x] DateRange uses defaultSelected prop which takes an object with `start` and `end` keys with values as moment() objects.
- [x] defaultSelected prop is not firing the date range query in DateRange component.

**Comment by farhan687** [comment]
Fixed here: f45a6f97703a523100b93f0d4cbec68381a931cf f288e3ca8c6b9b086d2d345346d1b0118344cf47

**Comment by siddharthlatest** [comment]
- [ ] defaultSelected prop is not firing the date range query in DateRange component.
