### ISSUE TITLE
selectAll can't be defaultSelected

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#63]
Codepen showing the issue - http://codepen.io/sids-aquarius/pen/ZeLOGe.

```
<MultiList
  componentId="CategorySensor"
  appbaseField="deal"
  selectAllLabel="All"
  defaultSelected={["All"]}
/>
```

It doesn't throw any error / warnings in the console, but at the same time it doesn't select the "All" label.

Can we also check if this issue happens with:

- [ ] MultiDropdownList
- [ ] MultiDropdownRange
- [ ] MultiRange

**Comment by farhan687** [comment]
@siddharthlatest `selectAllLabel` prop is available in **Singlelist, MultiList, SingleDropdown and MultiDropdown** components.

I have tested all 4 components and fixed over here: 74b453450072cccbbcbbea3035927b05c0f155a7 a6f8bf3e275cd636ad3ec59321e8c419b5e80384
