### ISSUE TITLE
MultiList filters don't show up on Internet Explorer (?)

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#64]
* A user couldn't see the MultiList filters on Internet Explorer but could when they switched to Google Chrome / Firefox.

Can we verify and if this is an issue, we should run a compatibility test with IE 11 for all the components in https://opensource.appbase.io/reactivebase/playground.

**Comment by farhan687** [comment]
Tested. 
All the components are working fine in IE 11.576

![ie-multilist](https://cloud.githubusercontent.com/assets/6059027/23949813/c4f6eac2-09ae-11e7-8c16-d7d0a48c80c3.png)

**Comment by siddharthlatest** [comment]
@farhan687 what was the issue here, and how did we fix it?

**Comment by siddharthlatest** [comment]
@farhan687 
- [ ] We will test playground using Browserstack and then come back to the issue.

**Comment by farhan687** [comment]
Tested in internet explorer, edge, firefox browsers through BrowserStack and playground is working fine over there.
