### ISSUE TITLE
Support 'credentials' parameter in lieu of 'username' and 'password' in ReactiveBase HOC

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#65]
Starting appbase-js v0.11.0 as well as with the new UI, we are concatenating username:password fields into a single `credentials` field. Starting v1.0.0-alpha{i}, we should make a breaking change to support `credentials` instead of `username:password`.

When a user uses the username:password fields, we will add an intuitive warning message along the lines of "ReactiveBase expects credentials as a prop instead of username:password."

Before releasing this change, we need to update:
- [ ] All ReactiveMaps and ReactiveSearch examples.
- [x] All playground stories.
- [x] All doc references.

**Comment by farhan687** [comment]
Fixed over here: f10ca544d8d486da0f2ac8a87fce59eb20b06ffe 8f561362ff2b2e0f5bb331367ee32f66b0e9117d

**Comment by siddharthlatest** [comment]
@farhan687 Have we updated this in ReactiveMaps example?

@metagrover Are you using credentials in all ReactiveSearch examples?

**Comment by metagrover** [comment]
Yes, all ReactiveSearch examples and stories use `credentials`
