### ISSUE TITLE
ToggleButton's defaultSelected should accept String

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#71]
When multiSelect mode is off, ToggleButton component's defaultSelected prop should accept a `String` value.

Currently, it throws a
```
Warning: Failed prop type: Invalid prop `defaultSelected` of type `string` supplied to `ToggleButton`, expected `array`.
```

**Comment by farhan687** [comment]
Fixed here: a94d593e4701cb4428ff3a25919d82792b8969eb
