### ISSUE TITLE
DataController style behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#75]
- [x] **rbc-querylabel-active** class should be **rbc-datalabel-active**.
- [x] Change **showUI** prop name to **visible**, and create a CSS class **rbc-visible-active** when the prop is set to true and **rbc-visible-inactive** when the prop value is false.

- [x] Create an annotated image for the DataController component.

**Comment by farhan687** [comment]
Fixed here: 1706150209320434031d22490e6f6ae021f543dc
