### ISSUE TITLE
Include pagination prop in ReactiveList

### ISSUE THREAD

**Issue by farhan687** [appbaseio/reactivebase#76]
- Include `pagination` prop in ReactiveList and remove `ReactivePaginatedList` component.

**Comment by siddharthlatest** [comment]
We will also include a CSS style class for the same, `rbc-pagination-active` and `rbc-pagination-inactive`.

**Comment by farhan687** [comment]
Fixed here: bcfbcaa443f8a56b62c7909bb22d88eb53ef7be3 017cb54e2d3e00ae0741fe4734379ea2d55e7801
