### ISSUE TITLE
MultiList has an issue with its default query

### ISSUE THREAD

**Issue by farhan687** [appbaseio/reactivebase#82]
MultiList component applies a query even when no values are selected using an empty array.

Possible fix: We should do an empty array validation before applying the query.

**Comment by farhan687** [comment]
Fixed here 5fe5094723a682ffa87dd0fdb68a43da715744d6

**Comment by siddharthlatest** [comment]
@farhan687 Seeing this issue after upgrading to v1.0.0-alpha11 version.

**Comment by farhan687** [comment]
@siddharthlatest Can you write the steps to replicate the issue?

**Comment by siddharthlatest** [comment]
This was an issue with build dependency of reactivebase under reactivemaps, it was using an older build version because of string matching.
