### ISSUE TITLE
ReactiveList: Last Line Hide Issue

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#87]
Currently, we initially show a last line during ReactiveList rendering and then we remove after a few seconds.

Initial Render:

![](https://i.imgur.com/6xn2eJE.png) 

After:

![](https://i.imgur.com/DLVVSe2.png)

**Comment by farhan687** [comment]
@siddharthlatest We are not hiding the last line but we are enabling the scroll over there to fetch new records while user scroll it to bottom.

**Comment by siddharthlatest** [comment]
@farhan687 Can we either not show the last line always or show it always? It seems the enabling of scroll has a side-effect here.

**Comment by farhan687** [comment]
Fixed here: 8b2469e3646bc902106e31aa1bfcbf5ed9b18e84
