### ISSUE TITLE
DateRange: Support Range Use-case

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#88]
The current **DateRange** component uses a single appbaseField and runs a range query on that field. But there are scenarios where a **DateRange** component can actually be querying the range against a `from` and `to` field in a dataset.

To support both of these use-cases, we can support two distinct formats for DateRange:

1. appbaseField `String` - will run a range query on the specified field.  
2. appbaseField `Array` ["from_field", "to_field"] - will run two range queries that satisfy both these fields. It is important that the **from_field** appears before the **to_field** and that the array only has two elements and both have `String` data type.

**Comment by farhan687** [comment]
Fixed here: cd485563512b639b3a70166423f732840cf5ce19
