### ISSUE TITLE
Date components styling behavior

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase#90]
Color themes do not work well with Date components

![screen shot 2017-04-06 at 7 51 11 pm](https://cloud.githubusercontent.com/assets/9116042/24759273/9cf68a72-1b02-11e7-8983-603250c82867.png)

**Comment by farhan687** [comment]
Fixed here: 91c4cf0800e1365660e4ac82aafa2c368c411778

**Comment by siddharthlatest** [comment]
@farhan687 Has this been released? Not working with alpha13 release.
