### ISSUE TITLE
DataSearch: Highlight prop

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#91]
Add a **highlight** prop in the DataSearch component. The implementation would use the highlighting query functionality https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html to add highlights to the result data.

Currently, we will default it to **false**.

**Comment by farhan687** [comment]
Fixed here: 6728928367f21ce0d7da83f08b4b9cbf35b9da1a
