### ISSUE TITLE
DataSearch: Jumping Search Results

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#96]
When paginating the search results, the pages return different results, i.e. the search order is not preserved.

- [x] Apply the `preference` query string parameter with a custom value to ensure the query hits the same shards for the same preference value.

**Comment by farhan687** [comment]
Fixed here 2fcd186d9c7bfc097b0c40c1cd968b534fd0d091

**Comment by farhan687** [comment]
- [ ] Fix scroll issue when pagination is applied.

**Comment by siddharthlatest** [comment]
N/A in ReactiveBase.
