### ISSUE TITLE
Unique *key* prop  warning on using sortOptions

### ISSUE THREAD

**Issue by devAbnull** [appbaseio/reactivebase#97]
On using `sortOptions` in ReactiveList warning is generated:
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ReactiveList`.
in option (created by ReactiveList)
    in ReactiveList  ...

![screenshot from 2017-04-11 18 53 36](https://cloud.githubusercontent.com/assets/16541261/24911344/3dee4c38-1ee8-11e7-890c-2c69987e3499.png)

**Comment by siddharthlatest** [comment]
Cannot replicate the issue.
